server:
  port: 9000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/spring_app_db?useLegacyDatetimeCode=false 
    username: app_user
    password: test123
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

liquibase:

logging:
  level:
    root: INFO
    com.chornyi: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO


# ===================================================================
# Application specific properties
# ===================================================================

application:
  vigilante-api: https://ipvigilante.com/json/

  swagger:
    base-package: com.chornyi.spring.boot.thymeleaf.web.rest
    title: Thymeleaf REST API Services
    description: The services which are expose API for the Thymeleaf Service
    version: 0.0.1
    terms-of-service-url: Terms of service
    contact-name: Taras Chornyi
    contact-url: https://github.com/taras-chornyi
    contact-email: taras.chornyi@gmail.com
    license: Apache License Version 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0

  ldap:
    enable: false
    url: ldap://localhost:10389/
    baseDn: dc=example,dc=com
    username: uid=admin,ou=system
    password: secret
    userDnPattern: uid={0},ou=Users
